defaults:
  - default.yaml

base_path: /datasets/waymo
tag: 'mini'

train_data_path: [ "${paths.base_path}/processed/mini/training" ] # list of paths to the training data
train_data_tag: ["mini-training"]
val_data_path: ["${paths.base_path}/processed/mini/validation" ] # list of paths to the validation data
val_data_tag: ["mini-validation"]
test_data_path: [
  "${paths.base_path}/processed/mini/validation",
  "${paths.base_path}/processed/mini/testing",
  "${paths.base_path}/processed/mini_causal/validation",
  "${paths.base_path}/processed/mini_causal/testing",
]
test_data_tag: ["mini-validation", "mini-testing", "mini-causal-validation", "mini-causal-testing"]
