default_stages:
  - pre-commit
  - manual

default_language_version:
  python: python3.12

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.1
    hooks:
      - id: ruff-check
        args: ["--fix"]
        always_run: true
        pass_filenames: false
      - id: ruff-format
        always_run: true
        pass_filenames: false

  # Pyright
  - repo: local
    hooks:
      - id: pyright
        name: pyright type check
        entry: pyright
        # entry: uv run pyright
        language: python
        types: [python]
        args: ["--project", "pyproject.toml", "src"]
        pass_filenames: false
        always_run: true

  # Scans staged files for hardcoded passwords, tokens, and keys
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets

  - repo: https://github.com/google/keep-sorted
    rev: v0.7.1 # Use the desired version of keep-sorted
    hooks:
      - id: keep-sorted

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      # Prevents accidentally committing huge files. Limit set to 1MB.
      - id: check-added-large-files
        args: ["--maxkb=1024"]
        exclude: |
          (?x)^(
              assets/animated_scenario_high.gif |
              assets/animated_scenario_low.gif |
          )$
      # Detects filename case conflicts on case-insensitive filesystems
      - id: check-case-conflict
      # Check that anything with a shebang has the executable bit set
      - id: check-executables-have-shebangs
      # Ensures all files end with a newline (avoids diff noise)
      - id: end-of-file-fixer
      # Removes trailing whitespace in all files
      - id: trailing-whitespace
      # Forbids submodules
      - id: forbid-submodules
      # Don't allow commits to main
      - id: no-commit-to-branch
        args: ["--branch=main"]
      # Validates YAML file syntax
      - id: check-yaml
      # Validates JSON file syntax
      - id: check-json
      # Validates TOML file syntax
      - id: check-toml
      # Blocks commit if leftover merge conflict markers exist
      - id: check-merge-conflict
      # Detect private key
      - id: detect-private-key
