defaults:
  - model_checkpoint.yaml
  - early_stopping.yaml
  - model_summary.yaml
  - rich_progress_bar.yaml
  - lr_monitor.yaml
  - _self_

model_checkpoint:
  dirpath: ${paths.ckpt_path}/${exp_name}
  filename: "epoch_{epoch:03d}"
  monitor: "val/brierFDE"
  mode: "min"
  save_last: True
  auto_insert_metric_name: False
  save_weights_only: True

early_stopping:
  monitor: "val/brierFDE"
  mode: "min"
  patience: 10

model_summary:
  max_depth: -1
