defaults:
  - override hydra_logging: colorlog
  - override job_logging: colorlog

output_subdir: null
run:
  dir: ./out/

sweep:
  dir: ./out/

job_logging:
  handlers:
    file:
      filename: ./out/${hydra.job.name}.log
