_target_: pytorch_lightning.trainer.Trainer

default_root_dir: ${paths.output_dir}

min_epochs: 1 # prevents early stopping
max_epochs: ${model.config.max_epochs}

accelerator: cpu
devices: 1

gradient_clip_val: ${model.config.grad_clip_norm}
# mixed precision for extra speed-up
# precision: 16

# perform a validation loop every N training epochs
check_val_every_n_epoch: 1

# set True to to ensure deterministic results
# makes training slower but gives more reproducibility than just setting seeds
deterministic: True

profiler: simple
