
tag: scenario-static
visualizer:
  _target_: scenetokens.utils.scenario_visualizers.scenario.ScenarioVisualizer
  config:
    scenario_type: gt
    is_ego_centric: false

    static_map_keys:
      - lane
      - crosswalk
      - speed_bump
      - road_edge
      - road_line
      - stop_sign

    dynamic_map_keys:
      - stop_point

    map_colors:
      lane: "k"
      crosswalk: "cyan"
      speed_bump: "orange"
      road_edge: "k"
      road_line: "k"
      stop_sign: "red"
      stop_point: "purple"

    map_alphas:
      lane: 0.1
      crosswalk: 0.6
      speed_bump: 0.6
      road_edge: 0.1
      road_line: 0.1
      stop_sign: 0.8
      stop_point: 0.8

    agent_colors:
      TYPE_PEDESTRIAN: "green"
      TYPE_CYCLIST: "cyan"
      TYPE_VEHICLE: "grey"
      TYPE_SDC: "red"
      TYPE_RELEVANT: "orange"
      TYPE_RELEVAN: "orange"
