# @package _global_
palette: muted

seed: 42 # Seed for random generators
base_path: ./datasets/waymo/causal-benchmark-labeled/model_comparison

metric_analysis_type: sample_selection_analysis # Either of 'group_analysis' or 'sample_selection_analysis'

# If 'metric_analysis_type' is 'group_analysis', assumes a specific group format which was created manually from
# MLflow -> Google Sheets -> CSV file with all metrics per experiment in the group.
group_name: student_bests
group_file: ${base_path}/${group_name}.csv

# If 'metric_analysis_type' is 'sample_selection_analysis', assumes metrics are organized in a tabular format following
# MLflow's organization by simply downloading all runs into a CSV file and compares them directly by querying that
# table for the specified experiments.

metrics_to_compare: [
  # Trajectory Forecasting Metrics
  'brierFDE',
  'minFDE6',
  'minADE6',
  'missRate',
  # Causal Classification Metrics
  'causalTP',
  'causalTN',
  'causalFP',
  'causalFN',
  'f1Score',
  'precision',
  'recall',
]
splits_to_compare: ['testing']
