# @package _global_

# Tokenization Analyses:
# Each tag that starts with 'run_' represents a type of analysis. Corresponding configuraion parameters for each of
# these analyses are below each tag.

# Produces a histograms over the tokenized scenarios, representing token-utilization.
run_scenario_class_distribution: false
best_mode_only: true # if true, it only considers the token from the 'best' predicted mode
rank_by_probability: true # if true and 'best_mode_only: false', it will rank the tokens based on the mode probability.

# Token consistency analysis
run_token_consistency_analysis: false
consistency_measure: hamming # either of 'jaccard' or 'hamming'

# Group uniqueness analysis
run_group_uniqueness_analysis: false
normalize_counts: 'group_scenarios' # either of 'all_scenarios' or 'group_scenarios' or 'none'

# Inter-group uniqueness
run_intergroup_analysis: false

# Produces a visualization of the scenario embeddings using dimensionality reduction methods.
run_dim_reduction_analysis: false
dim_reduction_algorithm: tsne # either of 'tsne' or 'umap'
num_components: 2
reduce: input_embedding # either of 'input_embedding' or 'quantized_embedding'
normalize: true
alpha_type: none # either of 'scores' or 'class_counts' or 'none'
save_result: true

# Produces a per-class score analysis over the scenarios and visualizes scored scenarios by percentile.
run_score_analysis: false
vis_scored_scenarios: false
group_by_token: true # group the scenarios by predicted token
percentiles_of_interest: [10, 25, 50, 75, 90, 95] # score percentile ranges that will be analyzed

# TO-DO
run_class_overlap_analysis: false
run_viz_scenarios_in_tsne: false
